---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  ports:
    - name: frontend
      port: 80
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  ports:
    - name: backend
      port: 9000
  selector:
    app: backend
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  ports:
    - name: db
      port: 5432
  selector:
    app: database


