---
apiVersion: v1
kind: Service
metadata:
  name: endpoint-identme
spec:
  type: NodePort
  ports:
    - name: endpoint-identme
      port: 8080
      nodePort: 31234
---
apiVersion: v1
kind: Endpoints
metadata:
  name: endpoint-identme
subsets:
  - addresses:
      - ip: 49.12.234.183
    ports:
      - name: endpoint-identme
        port: 80

