apiVersion: v1
kind: Pod
metadata:
  labels:
    app: alpine
  name: alpine
  namespace: app-namespace
spec:
  containers:
    - args:
        - sleep
        - "60"
      image: alpine
      name: alpine
      imagePullPolicy: IfNotPresent
