apiVersion: v1
kind: Pod
metadata:
  labels:
    app: fedora
  name: fedora
spec:
  containers:
  - image: fedora
    name: fedora
    env:
    - name: VAULT_TOKEN
      valueFrom:
        secretKeyRef:
          name: app-data
          key: TOKEN
    imagePullPolicy: IfNotPresent
    command:
    - /bin/sh
    args: ["-c", "dnf -y install pip; pip install hvac; sleep 3600"]
    #- sh
    #args: [ "-c", "sleep 3600" ]
    volumeMounts:
    - name: application
      mountPath: "/root/app"
  restartPolicy: Never

  volumes:
  - name: application
    secret:
      secretName: app-data
      defaultMode: 0555
      items:
      - key: test-app
        path: test_app.py