---
apiVersion: v1
kind: Secret
metadata:
  name: app-data
type: Opaque
stringData:
  TOKEN: aiphohTaa0eeHei
  test-app: |
    #!/usr/bin/env python3
    import hvac
    import os
    
    vault_token = os.getenv('VAULT_TOKEN')
    
    client = hvac.Client(
      url='http://vault:8200',
      token=vault_token
    )
    
    result_message = ''
    
    try:
      secret = client.secrets.kv.v2.read_secret_version(
        path='my_secret'
      )
      result_message = secret['data']['data']
    except hvac.exceptions.InvalidPath:
      result_message = 'There is no any secrets((('
    
    print(result_message)
