---

- name: prepare control-plane
  hosts: node1
  tasks:

  - name: install utilities
    become: true
    apt:
      name: "{{ item }}"
      update_cache: true
    loop:
      - git
      - python3-pip

  - name: clone kubespray
    git:
      repo: https://github.com/kubernetes-sigs/kubespray.git
      dest: ~/kubespray

  - name: install requirements
    pip:
      requirements: ~/kubespray/requirements.txt

  - name: copy inventory
    copy:
      src: ./hosts.yml
      dest: ~/kubespray/hosts.yml

  - name: generate ssh keys
    shell: ssh-keygen -q -f ~/.ssh/id_rsa -N ''
    args:
      creates: ~/.ssh/id_rsa

  - name: copy ssh pub from server
    fetch:
      src: ~/.ssh/id_rsa.pub
      dest: "/tmp/"
      flat: yes

  - name: copy manifests for tests
    tags: test
    become: true
    copy:
      src: manifests
      dest: ~/

- name: some tasks for all hosts
  hosts: all
  tasks:

  - name: add pubkey for all hosts
    authorized_key:
      user: "{{ ansible_user }}"
      state: present
      key: "{{ lookup('file', '/tmp/id_rsa.pub') }}"

- name: install calicoctl
  hosts: node1
  tasks:

  - name: download calicoctl
    become: true
    get_url:
      url: https://github.com/projectcalico/calico/releases/download/v3.24.5/calicoctl-linux-amd64
      dest: /usr/local/bin/calicoctl
      mode: 0755

#- name: run kubespray
#   hosts: node1
#   tasks:
#
#   - shell: cd kubespray && ansible-playbook -b -i hosts.yaml cluster.yaml
