{
 "title": "Homework dashboard",
 "description": "Дашборд для второго задания",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Node_exporter CPU",
   "type": "stat",
   "description": "Утилизация CPU для nodeexporter (в процентах, 100-idle)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " 100 - (avg by(instance) (rate(node_cpu_seconds_total{job=\"node_exporter\", mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{job=\"node_exporter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load5{job=\"node_exporter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load15{job=\"node_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"node_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free disks space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=\"localhost:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}