apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  containers:
  - image: nginx:stable
    name: nginx
    imagePullPolicy: IfNotPresent
    env:
    - name: TEST_ENV
      valueFrom:
        secretKeyRef:
          name: env-val
          key: TEST_STRING
    volumeMounts:
    - name: certs
      mountPath: "/etc/nginx/conf/certs"
      readOnly: true
    - name: ssl-conf
      mountPath: "/etc/nginx/conf.d"
      
  volumes:
  - name: certs
    secret:
      secretName: tls-cert
  - name: ssl-conf
    persistentVolumeClaim:
      claimName: pvc-nginx